apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    app: httpd
spec:
  containers:
    - image: docker.io/centos/nginx-112-centos7
      name: nginx1
      ports:
        - containerPort: 8080
