apiVersion: v1
kind: Pod
metadata:
  name: jenkins1
  labels:
    app: httpd
spec:
  containers:
    - image: docker.io/openshift/jenkins-2-centos7
      name: jenkins1
      ports:
        - containerPort: 8080
